language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t skyosev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skyosev/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-614028860512"
  bucker_path: "docker-react"
  on: 
    branch: master